#!/usr/bin/env python3
"""
oracle_diff.py — exact-match verification against a naive/reference implementation.

Part of the algo-architect skill, bucket 1 (exact/behavior-preserving
techniques: alpha-beta vs. minimax, FFT vs. naive DFT, Hungarian vs.
brute-force assignment, Rete vs. naive full re-evaluation, an optimized
implementation vs. its own simpler predecessor, etc.).

WHY THIS EXISTS
For a behavior-preserving optimization, ANY difference in output between
the reference and the candidate is a bug — there's no "acceptable drift"
the way there is for heuristic or tunable techniques. This harness runs
both implementations on the same inputs (existing test files, or inputs
freshly generated by a generator command) and reports the first divergence
it finds, with the offending input saved to disk for debugging.

Both implementations are run as arbitrary shell commands, so this works
regardless of what language either one is written in.

USAGE

  Compare against a directory of existing test-case files:
    python3 oracle_diff.py \\
        --reference "./naive_dft {input}" \\
        --candidate "./fft {input}" \\
        --inputs-dir tests/signals/ \\
        --numeric-tolerance 1e-6

  Compare against freshly generated random inputs (a generator command that
  writes one test case to stdout given a seed):
    python3 oracle_diff.py \\
        --reference "./brute_force_assign {input}" \\
        --candidate "./hungarian {input}" \\
        --generate "./gen_random_matrix.py --seed {seed}" \\
        --count 200

  If a command doesn't contain "{input}", the input is piped to it on
  stdin instead of passed as an argument.

COMPARISON MODES
  - Exact (default): stdout must match byte-for-byte (trailing whitespace
    on each line and a trailing newline are ignored).
  - --numeric-tolerance EPS: both outputs are tokenized on whitespace,
    parsed as floats, and compared elementwise within EPS. Use this for
    floating-point-heavy outputs (FFT, Simplex, etc.) where exact string
    equality isn't the right bar.

OUTPUT
  A summary of how many inputs were tested and how many diverged. On the
  first divergence (or every divergence, with --continue-on-failure), the
  offending input is saved under --failures-dir and both outputs are
  printed, so the smallest reproducer is immediately available.

  Exit code: 0 if every input matched, 1 if any diverged, 2 on a setup/
  usage error.
"""

import argparse
import shlex
import subprocess
import sys
import tempfile
from pathlib import Path


def run_command(template: str, input_path: Path, timeout: float) -> tuple[str, int, bool]:
    """Run a command template against one input file. Returns (stdout, returncode, timed_out)."""
    if "{input}" in template:
        cmd = shlex.split(template.format(input=str(input_path)))
        stdin_data = None
    else:
        cmd = shlex.split(template)
        stdin_data = input_path.read_text()

    try:
        proc = subprocess.run(
            cmd, input=stdin_data, capture_output=True, text=True, timeout=timeout
        )
        return proc.stdout, proc.returncode, False
    except subprocess.TimeoutExpired:
        return "", -1, True


def outputs_match(a: str, b: str, numeric_tolerance: float | None) -> bool:
    if numeric_tolerance is None:
        norm_a = "\n".join(line.rstrip() for line in a.splitlines())
        norm_b = "\n".join(line.rstrip() for line in b.splitlines())
        return norm_a == norm_b

    tokens_a, tokens_b = a.split(), b.split()
    if len(tokens_a) != len(tokens_b):
        return False
    try:
        for ta, tb in zip(tokens_a, tokens_b):
            if abs(float(ta) - float(tb)) > numeric_tolerance:
                return False
        return True
    except ValueError:
        # Non-numeric tokens present alongside --numeric-tolerance: fall back to exact match
        return a.strip() == b.strip()


def gather_inputs(args) -> list[Path]:
    if args.inputs_dir:
        inputs = sorted(p for p in Path(args.inputs_dir).iterdir() if p.is_file())
        if not inputs:
            print(f"error: no files found in {args.inputs_dir}", file=sys.stderr)
            sys.exit(2)
        return inputs

    # Generated inputs: run the generator once per seed, save each to the failures dir's
    # sibling temp area so they exist as real files the reference/candidate commands can read.
    gen_dir = Path(tempfile.mkdtemp(prefix="oracle_diff_generated_"))
    inputs = []
    for seed in range(args.seed_start, args.seed_start + args.count):
        gen_cmd = shlex.split(args.generate.format(seed=seed))
        proc = subprocess.run(gen_cmd, capture_output=True, text=True, timeout=args.timeout)
        if proc.returncode != 0:
            print(f"error: generator failed for seed {seed}: {proc.stderr}", file=sys.stderr)
            sys.exit(2)
        path = gen_dir / f"generated_seed_{seed}.txt"
        path.write_text(proc.stdout)
        inputs.append(path)
    return inputs


def main():
    parser = argparse.ArgumentParser(
        description="Exact-match verification of a candidate implementation against a reference (algo-architect, bucket 1).",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--reference", required=True, help='Reference command, e.g. "./naive {input}"')
    parser.add_argument("--candidate", required=True, help='Candidate command, e.g. "./optimized {input}"')

    src_group = parser.add_mutually_exclusive_group(required=True)
    src_group.add_argument("--inputs-dir", help="Directory of existing input files, one test case per file")
    src_group.add_argument("--generate", help='Generator command with a {seed} placeholder, e.g. "./gen.py --seed {seed}"')

    parser.add_argument("--count", type=int, default=100, help="Number of generated inputs (with --generate; default 100)")
    parser.add_argument("--seed-start", type=int, default=0, help="First seed to use (with --generate; default 0)")
    parser.add_argument("--numeric-tolerance", type=float, default=None,
                         help="Compare outputs as whitespace-separated floats within this tolerance, "
                              "instead of exact string match")
    parser.add_argument("--timeout", type=float, default=10.0, help="Per-run timeout in seconds (default 10)")
    parser.add_argument("--continue-on-failure", action="store_true",
                         help="Keep testing after a divergence instead of stopping at the first one")
    parser.add_argument("--failures-dir", default="oracle_diff_failures",
                         help="Where to save inputs that produced a divergence (default ./oracle_diff_failures)")
    args = parser.parse_args()

    inputs = gather_inputs(args)
    failures_dir = Path(args.failures_dir)

    total = len(inputs)
    failed = 0
    for i, input_path in enumerate(inputs):
        ref_out, ref_code, ref_timeout = run_command(args.reference, input_path, args.timeout)
        cand_out, cand_code, cand_timeout = run_command(args.candidate, input_path, args.timeout)

        problem = None
        if ref_timeout or cand_timeout:
            problem = f"timeout (reference {'timed out' if ref_timeout else 'ok'}, candidate {'timed out' if cand_timeout else 'ok'})"
        elif not outputs_match(ref_out, cand_out, args.numeric_tolerance):
            problem = "output mismatch"

        if problem:
            failed += 1
            failures_dir.mkdir(parents=True, exist_ok=True)
            saved_path = failures_dir / f"failure_{failed}{input_path.suffix or '.txt'}"
            saved_path.write_text(input_path.read_text())
            print(f"[{i + 1}/{total}] DIVERGENCE ({problem}) — input saved to {saved_path}")
            print(f"  reference (exit {ref_code}): {ref_out[:500]!r}")
            print(f"  candidate (exit {cand_code}): {cand_out[:500]!r}")
            if not args.continue_on_failure:
                break
        elif args.continue_on_failure or True:
            pass  # keep going silently on success; summary printed at the end

    print()
    print(f"Tested {min(i + 1, total)}/{total} inputs — {failed} divergence(s) found.")
    if failed:
        print(f"Failing inputs saved under {failures_dir}/")
        sys.exit(1)
    else:
        print("All outputs matched.")
        sys.exit(0)


if __name__ == "__main__":
    main()
